#!/usr/bin/env python3
import sys

usage = "please run it right :eyes:"
charLimit = 50

try:
    mode = sys.argv[1]
    url = sys.argv[2]
except IndexError:
    print(usage)
    exit(1)

modes=["auto", "video", "reddit", "webpage", "website"]

if mode not in modes:
    print("'{}' is not a valid mode. Please specify a mode from: {}".format(mode, modes))

elif mode == modes[3]:
    print("Treating link as webpage")
    try:
        from archivenow import archivenow
    except ModuleNotFoundError as e:
        print("Please install archivenow from https://github.com/oduwsdl/archivenow to download webpages.")
        # TODO: implement wget backup
        exit(1)
    # TODO: implement cmd filename import
    print("No filename specified, generating hash to use as filename")
    from hashlib import sha256
    filename = sha256(url.encode()).hexdigest()[0:charLimit]
    archivedUrl = archivenow.push(url, "warc", {"warc": filename})
    archivedUrl = archivenow.push(url, "ia")
    import os
    os.setxattr(filename+".warc", "user.url", url.encode())
    with open(filename+".url", "w") as f:
        f.write(url)

